/**
 * Liste de domaines d’emails jetables / temporaires.
 * Inscrire avec un de ces domaines est refusé à l’inscription.
 * Pour une liste étendue : npm package "disposable-email-domains" ou fichier externe.
 */
export const DISPOSABLE_EMAIL_DOMAINS = new Set<string>([
  '10minutemail.com',
  '10minutemail.net',
  'guerrillamail.com',
  'guerrillamail.org',
  'guerrillamail.net',
  'guerrillamail.biz',
  'guerrillamailblock.com',
  'temp-mail.org',
  'tempmail.com',
  'tempmail.net',
  'tempmail.co',
  'fakeinbox.com',
  'trashmail.com',
  'throwaway.email',
  'mailinator.com',
  'mailinator.net',
  'mailinator2.com',
  'yopmail.com',
  'yopmail.fr',
  'getnada.com',
  'sharklasers.com',
  'guerrillamail.info',
  'grr.la',
  'spam4.me',
  'dispostable.com',
  'maildrop.cc',
  'tempail.com',
  'tmpeml.com',
  'mohmal.com',
  'emailondeck.com',
  'mintemail.com',
  '33mail.com',
  'inboxkitten.com',
  'dropmail.me',
  'tempinbox.co.uk',
  'mytrashmail.com',
  'trashmail.ws',
  'anonymbox.com',
  'jetable.org',
  'jetable.com',
  'mailnesia.com',
  'mailcatch.com',
  'tempinbox.com',
  'discard.email',
  'discardmail.com',
  'getairmail.com',
  'tempmailo.com',
  'mytemp.email',
  'mytempmail.com',
  'emailfake.com',
  'fake-mail.tk',
  'mail-temp.com',
  'temp-mail.live',
  'temp-mail.io',
  'minuteinbox.com',
  'mintemail.com',
  'throwawaymail.com',
  'mail-temporaire.fr',
  'temp-mail.org',
  'disposable.com',
  'mailinator.com',
  'tempr.email',
  'temp-mail.ru',
  'mohmal.in',
  'mohmal.tech',
]);

export function isDisposableEmailDomain(domain: string): boolean {
  if (!domain || typeof domain !== 'string') return false;
  return DISPOSABLE_EMAIL_DOMAINS.has(domain.trim().toLowerCase());
}
